services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5500:5432
    volumes:
      - ~/apps/postgres_nanosaas:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=nanosaas
